### ISSUE TITLE
more icons

### ISSUE THREAD

**Issue by brianteeman** [angieradtke/Accessibility-plugin-icons#1]
I am trying to update and fix the accessibility toolbar.  There are a few new features. Could you create a few more icons please

increase line height
decrease line height
disable animations

and finaly one that will be a link to an accessibility statement.

This screenshot shows all the icons in action when using material icons

![image](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1296369/feb65eb5-0d2b-444f-b79b-f8077e655570)

**Comment by angieradtke** [comment]
Oh great,  that  you work on it: This is what  we have already, right?

![wheelchair](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/a55f8dc3-8681-47cc-9a55-69bb17383769)
![warning2](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/b95b7d19-9fd1-4ab5-a571-0323c94e2ce6)
![warning](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/a85946e9-0722-4ca3-9c32-86cffba062af)
![underline](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/f2760c6e-0ba3-41d1-bf3f-666ece3b8cd3)
![textincrease](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/554bb217-3eb0-406b-b2ab-04da323e655a)
![textdecrease](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/b1cab451-2b67-42af-bfc7-9df180d5f515)
![speak](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/55202482-2d83-4fc1-b7ba-8f4b1a7be648)
![signspaceincrease](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/6b7d92d3-ca6c-4c6d-a053-14d8a129e080)
![signspacedecrease](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/562cbc70-e85f-45be-923e-6768553dc5b2)
![signspace](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/141ae664-1fab-483e-a6f3-59ae78e8fe90)
![ruler](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/894370a9-a613-405a-8827-cf4d8ed009b7)
![reset](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/a5e9f160-0b51-4362-ad9e-7535e61f5027)
![mouse2](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/dcaa04a2-1612-44ed-8c28-b3b8f1e0c7de)
![mouse](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/d48e39d4-c65b-4bed-951e-280ee30863b4)
![invert](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/90326229-ff19-4469-8b06-37c5135365b6)
![grayscale2](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/d3aff60a-147e-44e5-a676-780625a81f44)
![grayscale](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/53ae7c3c-2f7e-41ec-9e7d-8d38453e1eb3)
![error](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/dea63684-79ab-4487-b3ce-0b5a83efa42a)
![close](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/fe32a9e9-69a3-44e5-aa63-8e7bfb3a44d9)

**Comment by brianteeman** [comment]
I am going to change the wheelchair to the universal accessibility icon

**Comment by angieradtke** [comment]
![no-animations](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/1cf3cddd-9cbc-4f20-a433-d628e916c17d)
![line-height-increase](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/79e5c55f-5c51-427d-982c-9a7574c16cc2)
![line-height-decrease](https://github.com/angieradtke/Accessibility-plugin-icons/assets/1172403/d463ad15-2e1b-4f6d-ac11-1c4e0aba17e7)

**Comment by brianteeman** [comment]
thank you

**Comment by brianteeman** [comment]
could you add them as files to this repo please - cant extract svg from the comments

**Comment by angieradtke** [comment]
https://github.com/angieradtke/Accessibility-plugin-icons here?

**Comment by brianteeman** [comment]
yes pLEase

**Comment by angieradtke** [comment]
done .-)
